### ISSUE TITLE
Departure/arrival stop and time more easily available

### ISSUE THREAD

**Issue by PasiSalenius** [HSLdevcom/OpenTripPlanner#113]
In many cases it is useful to get the first/last stop and departure/arrival time for a trip, perhaps for a large number of trips or patterns using a single query.

While the current graphQL API allows querying for all stops and stoptimes to get to this information, it feels cumbersome at best. Having to query all stops and stopime for long routes with many stops in them makes it currently slow or difficult to get to this data.

If possible, add departureStop, arrivalStop, departureStoptime, arrivalStoptime to all elements that support these.

**Comment by mjaakko** [comment]
Resolved by #217
