### ISSUE TITLE
Expose serviceDay value for Leg

### ISSUE THREAD

**Issue by PasiSalenius** [HSLdevcom/OpenTripPlanner#121]
Absolute stoptimes that can be converted to a unix time and on to valid Date objects require a serviceDay value. This value is returned for stoptimes returned to nearby departure and stoptimesForDate(serviceDay: ) queries.
```
{
  "scheduledArrival": 74400,
  "realtimeArrival": 74400,
  "scheduledDeparture": 74400,
  "realtimeDeparture": 74400,
  "serviceDay": 1485122400,
}
```
But it is not included in Legs returned to plan queries. As serviceDay changes at different times depending on route, not at midnight, it seems that there is no reliable way to get the correct serviceDay for stoptimes of trips of planned Legs, especially if they are at night time.

Add serviceDay as a value to Legs that are transitLegs.

**Comment by PasiSalenius** [comment]
Are there any plans to address this issue?

Either there is something I dont' currently understand, or there is no reliable way to know what serviceDay the trips (and stoptimes) in the route legs are supposed to use.

In the plan(...) routing graphQL request the client must use something like stoptimesForDate(serviceDay: "20170507") in the trip, but to get any serviceDay values at all an actual date must be included in the routing query. But at this point the client does not know what date the route legs will fall into, especially late at night.

IMHO there should be a way to get leg stoptimes, with correct serviceDay, by just including a stoptime child element for either the leg or trip of the leg.

@hannesj @samuliheljo @siren ?

**Comment by tuukka** [comment]
PR now here: https://github.com/HSLdevcom/OpenTripPlanner/pull/156
