### ISSUE TITLE
Slow responses for HFP cache queries

### ISSUE THREAD

**Issue by PasiSalenius** [HSLdevcom/OpenTripPlanner#139]
The following request for HFP cache takes several seconds to respond. Response delay was much smaller when I tried this some months ago, so something must be slowing these requests down currently.

https://api.digitransit.fi/realtime/vehicle-positions/v1/hfp/journey/tram/+/+/#

**Comment by siren** [comment]
That url is served by navigator-server. 

Do you constantly see is being slow or just occasionally. I added a check for that url: http://stats.pingdom.com/8m4jkk8to88b/2875786 and currently it tells me that the response time is less than 1 sec. Does your measurements agree?

**Comment by PasiSalenius** [comment]
The same request got much quicker the following day. Now it seems to be fine, as you said, with sub-second latency.

Good to have that Pingdom poller there, I'll refer to it in case I see further slowdowns.

I'll close the issue.
