### ISSUE TITLE
Add details for stoptimes index api

### ISSUE THREAD

**Issue by hannesj** [HSLdevcom/OpenTripPlanner#24]
- Mode of tripPattern
- Stop boarding/alighting status

**Comment by hannesj** [comment]
See opentripplanner/OpenTripPlanner#1815

**Comment by Trott** [comment]
It would make sense (to me, at least) for those to require the `detail` query parameter. But is it me or do the documented `detail` and/or `refs` flag have no effect?

On my instance, I've tried:

* http://localhost:8080/otp/routers/default/index/stops/ucsf%3Alhts/stoptimes/20150330?detail
* http://localhost:8080/otp/routers/default/index/stops/ucsf%3Alhts/stoptimes/20150330?detail=true
* http://localhost:8080/otp/routers/default/index/stops/ucsf%3Alhts/stoptimes/20150330?detail=long

But none of those results look any different than just:

* http://localhost:8080/otp/routers/default/index/stops/ucsf%3Alhts/stoptimes/20150330

Looking at `src/main/java/org/opentripplanner/index/IndexAPI.java`, I see the `detail` parameter being used in just one place but it's documented for a bunch of things at http://dev.opentripplanner.org/apidoc/0.15.0/resource_IndexAPI.html. Guess it would help if I tried to find out how the documentation gets generated....
