### ISSUE TITLE
Unable to run docker image in Google Cloud

### ISSUE THREAD

**Issue by manuelsilverio** [HSLdevcom/OpenTripPlanner#375]
**NOTE:** this issue system is intended for reporting bugs and tracking progress in software
development. For all other usage and software development questions or discussion, please write to
the user mailing list(https://groups.google.com/forum/#!forum/opentripplanner-users) or post a
question in the developer chat: https://gitter.im/opentripplanner/OpenTripPlanner.

## Expected behavior
Image should be deployed succesfully

## Observed behavior
When attempting to deploy image in cloud run I get the following error: 
* `Error retrieving graph source bundle https://api.digitransit.fi/routing-data/v2/finland/router-finland.zip from otp-data-server... retrying in 5 s...`

I think it could be related to the API key that is now needed to access routing data

## Version of OTP used (exact commit hash or JAR name)

I used the latest image from docker hub: https://hub.docker.com/r/hsldevcom/opentripplanner

## Command line used to start OTP
On the cloud shell of Google Cloud platform (linux) I used this:

* `docker pull hsldevcom/opentripplanner:latest`
* `docker tag hsldevcom/opentripplanner:latest gcr.io/helsinki-transport/hsldevcom/opentripplanner:latest`
* `docker push gcr.io/helsinki-transport/hsldevcom/opentripplanner:latest`

These commands pull tag and push the container image to the container registry of GCP.

## Steps to reproduce the problem

On GCP open the cloud shell and run this:

* `docker pull hsldevcom/opentripplanner:latest`
* `docker tag hsldevcom/opentripplanner:latest gcr.io/helsinki-transport/hsldevcom/opentripplanner:latest`
* `docker push gcr.io/helsinki-transport/hsldevcom/opentripplanner:latest`

* Then try to load container image in cloud run.

I hope I have provided enough information. Let me know if you need any more details.

**Comment by optionsome** [comment]
Hi, API key is now indeed required. You can find more information in https://digitransit.fi/en/developers/api-registration/ . We run this docker image within the same environment as where the data resides so we haven't needed the API keys in our calls and therefore the code lacks support for setting those keys. We are probably not going to add support for it in the near future but you can create a pr that adds the support and we can merge it. The file you need to edit is https://github.com/HSLdevcom/OpenTripPlanner/blob/dev-1.x/run.sh

**Comment by manuelsilverio** [comment]
Thanks, I will have a look at it and try to make it work.
