### ISSUE TITLE
Plan search fails to the some coordinates inside helsinki

### ISSUE THREAD

**Issue by antenehs** [HSLdevcom/OpenTripPlanner#62]
Plan search for the following coordinates fails with PathNotFoundException

`from: {lat: 60.168961, lon: 24.924713}, 
        to: {lat: 60.158830, lon: 24.933685`

The coordinates are valid but is in the middle of a house compound

https://www.google.fi/maps/place/60%C2%B009'31.8%22N+24%C2%B056'01.3%22E/@60.15822,24.9326136,17.33z/data=!4m5!3m4!1s0x0:0x0!8m2!3d60.15883!4d24.933685?hl=en

**Comment by tuukka** [comment]
Thanks for reporting - this seems to be a bug in OpenTripPlanner.

Remember that we use OpenStreetMap for the street network. You can see the building block and the problematic driveway (access:private, foot:destination, bicycle:destination, oneway:yes) here: http://www.openstreetmap.org/way/51548317

Using your coordinates, the routing fails indeed: https://beta.reittiopas.fi/reitti/Pohjoinen%20Rautatiekatu%2029%2C%20Helsinki%3A%3A60.168961%2C24.924713/Merikortteli%2C%20Helsinki%3A%3A60.158830%2C24.933685

Switching the direction works though: https://beta.reittiopas.fi/reitti/Merikortteli%2C%20Helsinki%3A%3A60.158830%2C24.933685/Pohjoinen%20Rautatiekatu%2029%2C%20Helsinki%3A%3A60.168961%2C24.924713

There's also one part of the driveway that is not tagged access:private, which can be part of the problem.

**Comment by hannesj** [comment]
This is related to using `org.opentripplanner.routing.edgetype.StreetEdge#isNoThruTraffic`

**Comment by Macroz** [comment]
Should we consider this again now that we are aiming to produce some results always?

**Comment by tuukka** [comment]
Seems to work now. Please re-open if this happens again.
