### ISSUE TITLE
Support for airplanes

### ISSUE THREAD

**Issue by samuliheljo** [HSLdevcom/OpenTripPlanner#7]
- [x] Server
- [x] OTP Client
- [ ] Navigator proto

**Comment by tpievila** [comment]
Needs some debugging to figure out why routing doesn't work. I'm able to get air trips from Helsinki to Kittilä, but not to Joensuu, Tampere or Rovaniemi. I'm guessing there's a problem in GTFS or OSM data.

**Comment by hannesj** [comment]
Pull request at opentripplanner/OpenTripPlanner#1733

**Comment by samuliheljo** [comment]
@tpievila Please also implement Navigator-proto client

**Comment by samuliheljo** [comment]
Waits for OTP 1.0 server

**Comment by tuukka** [comment]
Pull request at https://github.com/HSLdevcom/navigator-proto/pull/34
