### ISSUE TITLE
Please merge a commit from upstream to fix routing to stops when no OSM data

### ISSUE THREAD

**Issue by kalon33** [HSLdevcom/OpenTripPlanner#73]
With new linker, OTP lost ability to route to stops where no OSM data is available. This was re-implemented in https://github.com/opentripplanner/OpenTripPlanner/commit/deb25442797903a2f57c84f3f714be0145a856e0 could you please merge it?

Thanks!

**Comment by kalon33** [comment]
That was issue https://github.com/opentripplanner/OpenTripPlanner/issues/2282

**Comment by samuliheljo** [comment]
done
